In [ ]:
import pandas as pd
import numpy as np

url = "https://gist.githubusercontent.com/clairehq/79acab35be50eaf1c383948ed3fd1129/raw/407a02139ae1e134992b90b4b2b8c329b3d73a6a/winemag-data-130k-v2.csv"
reviews = pd.read_csv(url)

reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
reviews.describe()

         Unnamed: 0        points         price
count  65499.000000  65499.000000  60829.000000
mean   32749.000000     88.434037     35.232932
std    18908.076978      3.030310     39.477858
min        0.000000     80.000000      4.000000
25%    16374.500000     86.000000     17.000000
50%    32749.000000     88.000000     25.000000
75%    49123.500000     91.000000     42.000000
max    65498.000000    100.000000   2500.000000

In [ ]:
reviews.taster_name.describe()

count          51856
unique            19
top       Roger Voss
freq           13045
Name: taster_name, dtype: object

In [ ]:
reviews.region_1.describe()

count           54744
unique           1111
top       Napa Valley
freq             2226
Name: region_1, dtype: object

In [ ]:
reviews.points.describe()

count    65499.000000
mean        88.434037
std          3.030310
min         80.000000
25%         86.000000
50%         88.000000
75%         91.000000
max        100.000000
Name: points, dtype: float64

In [ ]:
reviews['points'].describe()

count    65499.000000
mean        88.434037
std          3.030310
min         80.000000
25%         86.000000
50%         88.000000
75%         91.000000
max        100.000000
Name: points, dtype: float64

In [ ]:
reviews.points.mean()

np.float64(88.43403716087269)

In [ ]:
list(reviews.taster_name.unique())

['Kerin O’Keefe',
 'Roger Voss',
 'Paul Gregutt',
 'Alexander Peartree',
 'Michael Schachner',
 'Anna Lee C. Iijima',
 'Virginie Boone',
 'Matt Kettmann',
 nan,
 'Sean P. Sullivan',
 'Jim Gordon',
 'Joe Czerwinski',
 'Anne Krebiehl\xa0MW',
 'Lauren Buzzeo',
 'Mike DeSimone',
 'Jeff Jenssen',
 'Susan Kostrzewa',
 'Carrie Dykes',
 'Fiona Adams',
 'Christina Pickard']

In [ ]:
reviews.taster_name.value_counts()

taster_name
Roger Voss            13045
Michael Schachner      7752
Kerin O’Keefe          5313
Paul Gregutt           4851
Virginie Boone         4696
Matt Kettmann          3035
Joe Czerwinski         2605
Sean P. Sullivan       2358
Anna Lee C. Iijima     2134
Jim Gordon             2032
Anne Krebiehl MW       1769
Lauren Buzzeo           938
Susan Kostrzewa         593
Jeff Jenssen            234
Mike DeSimone           231
Alexander Peartree      210
Carrie Dykes             45
Fiona Adams              11
Christina Pickard         4
Name: count, dtype: int64

In [ ]:
reviews.points.unique()

array([ 87,  86,  85,  88,  92,  91,  90,  89,  83,  82,  81,  80, 100,
        98,  97,  96,  95,  93,  94,  84,  99])

Convert in entry under points to point - mean(points)

---

In [ ]:
review_mean = reviews.points.mean()
def review_points_stnd(p):
  return p - review_mean

In [ ]:
stndpoints = reviews.points.map(review_points_stnd)

In [ ]:
stndpoints

0       -1.434037
1       -1.434037
2       -1.434037
3       -1.434037
4       -1.434037
           ...
65494    1.565963
65495    1.565963
65496    1.565963
65497    1.565963
65498    1.565963
Name: points, Length: 65499, dtype: float64

In [ ]:
type(reviews.points)

pandas.core.series.Series

In [ ]:
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

Convert each price entry from USD to CAD

In [ ]:
def usd_cad(p):
  return f"CAD {p*1.37}"
priceincad = reviews.price.map(usd_cad)
priceincad

0                       CAD nan
1                     CAD 20.55
2                     CAD 19.18
3        CAD 17.810000000000002
4         CAD 89.05000000000001
                  ...
65494    CAD 61.650000000000006
65495                 CAD 30.14
65496    CAD 27.400000000000002
65497    CAD 42.470000000000006
65498    CAD 13.700000000000001
Name: price, Length: 65499, dtype: object

In [ ]:
reviews.points.map(lambda p: p-review_mean)

0       -1.434037
1       -1.434037
2       -1.434037
3       -1.434037
4       -1.434037
           ...
65494    1.565963
65495    1.565963
65496    1.565963
65497    1.565963
65498    1.565963
Name: points, Length: 65499, dtype: float64

In [ ]:
reviews.price.map(lambda p: f"CAD {p*1.37}")

0                       CAD nan
1                     CAD 20.55
2                     CAD 19.18
3        CAD 17.810000000000002
4         CAD 89.05000000000001
                  ...
65494    CAD 61.650000000000006
65495                 CAD 30.14
65496    CAD 27.400000000000002
65497    CAD 42.470000000000006
65498    CAD 13.700000000000001
Name: price, Length: 65499, dtype: object

map() works on series, and apply() works on DataFrame

In [ ]:
def mean_points(row):
  row.points = row.points - review_mean
  return row

new_reviews = reviews.apply(mean_points, axis = 'columns')
new_reviews

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.434037,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.434037,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.434037,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.434037,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.434037,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65494,65494,France,Made from young vines from the Vaulorent porti...,Fourchaume Premier Cru,1.565963,45.0,Burgundy,Chablis,NaN,Roger Voss,@vossroger,William Fèvre 2005 Fourchaume Premier Cru (Ch...,Chardonnay,William Fèvre
65495,65495,Australia,"This is a big, fat, almost sweet-tasting Caber...",NaN,1.565963,22.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Tapestry 2005 Cabernet Sauvignon (McLaren Vale),Cabernet Sauvignon,Tapestry
65496,65496,US,"Much improved over the unripe 2005, Fritz's 20...",Estate,1.565963,20.0,California,Dry Creek Valley,Sonoma,NaN,NaN,Fritz 2006 Estate Sauvignon Blanc (Dry Creek V...,Sauvignon Blanc,Fritz
65497,65497,US,This wine wears its 15.8% alcohol better than ...,Block 24,1.565963,31.0,California,Napa Valley,Napa,NaN,NaN,Hendry 2004 Block 24 Primitivo (Napa Valley),Primitivo,Hendry
65498,65498,Spain,"A unique take on Manzanilla Sherry, which is o...",Manzanilla,1.565963,10.0,Andalucia,Jerez,NaN,Michael Schachner,@wineschach,Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...,Sherry,Bodegas Dios Baco S.L.

In [ ]:
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
reviews.loc[:,['price','points']]

       price  points
0        NaN      87
1       15.0      87
2       14.0      87
3       13.0      87
4       65.0      87
...      ...     ...
65494   45.0      90
65495   22.0      90
65496   20.0      90
65497   31.0      90
65498   10.0      90

[65499 rows x 2 columns]

In [ ]:
def column_summary(col):
  return col.mean()

reviews.loc[:,['price','points']].apply(column_summary, axis = 'index')

price     35.232932
points    88.434037
dtype: float64

In [ ]:
def column_function(col):

  return col.iloc[1:5]

In [ ]:
reviews.apply(column_function,axis = 'index')

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
def premium_label(row):
  if row.points >= 95 and row.price > 50:
    return "Premium"
  else:
    return "Normal"

reviews['label'] = reviews.apply(premium_label, axis = 'columns')

In [ ]:
reviews

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,label
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,Normal
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,Normal
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,Normal
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,Normal
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65494,65494,France,Made from young vines from the Vaulorent porti...,Fourchaume Premier Cru,90,45.0,Burgundy,Chablis,NaN,Roger Voss,@vossroger,William Fèvre 2005 Fourchaume Premier Cru (Ch...,Chardonnay,William Fèvre,Normal
65495,65495,Australia,"This is a big, fat, almost sweet-tasting Caber...",NaN,90,22.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Tapestry 2005 Cabernet Sauvignon (McLaren Vale),Cabernet Sauvignon,Tapestry,Normal
65496,65496,US,"Much improved over the unripe 2005, Fritz's 20...",Estate,90,20.0,California,Dry Creek Valley,Sonoma,NaN,NaN,Fritz 2006 Estate Sauvignon Blanc (Dry Creek V...,Sauvignon Blanc,Fritz,Normal
65497,65497,US,This wine wears its 15.8% alcohol better than ...,Block 24,90,31.0,California,Napa Valley,Napa,NaN,NaN,Hendry 2004 Block 24 Primitivo (Napa Valley),Primitivo,Hendry,Normal
65498,65498,Spain,"A unique take on Manzanilla Sherry, which is o...",Manzanilla,90,10.0,Andalucia,Jerez,NaN,Michael Schachner,@wineschach,Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...,Sherry,Bodegas Dios Baco S.L.,Normal

In [ ]:
def column_describe(col):

  return col.describe()

In [ ]:
reviews.apply(column_describe,axis = 'index')

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
25%,16374.500000,NaN,NaN,NaN,86.000000,17.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,32749.000000,NaN,NaN,NaN,88.000000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,49123.500000,NaN,NaN,NaN,91.000000,42.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
count,65499.000000,65467,65499,46588,65499.000000,60829.000000,65467,54744,25170,51856,49467,65499,65499,65499
freq,NaN,27177,3,999,NaN,NaN,18122,2226,5420,13045,13045,6,6657,119
max,65498.000000,NaN,NaN,NaN,100.000000,2500.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,32749.000000,NaN,NaN,NaN,88.434037,35.232932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN,80.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,18908.076978,NaN,NaN,NaN,3.030310,39.477858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,US,"Cigar box, café au lait, and dried tobacco aro...",Reserve,NaN,NaN,California,Napa Valley,Central Coast,Roger Voss,@vossroger,Korbel NV Brut Sparkling (California),Pinot Noir,Wines & Winemakers
unique,NaN,41,62824,24187,NaN,NaN,385,1111,17,19,15,62466,590,13549

In [ ]:
list(reviews.region_1.unique())

['Etna',
 nan,
 'Willamette Valley',
 'Lake Michigan Shore',
 'Navarra',
 'Vittoria',
 'Alsace',
 'Napa Valley',
 'Alexander Valley',
 'Central Coast',
 'Cafayate',
 'Mendoza',
 'Ribera del Duero',
 'Virginia',
 'Oregon',
 'Sicilia',
 'Paso Robles',
 'Sonoma Coast',
 'Terre Siciliane',
 'Cerasuolo di Vittoria',
 'Clarksburg',
 'Beaujolais-Villages',
 'Dry Creek Valley',
 'Sonoma Valley',
 'McMinnville',
 'Puglia',
 'Beaujolais',
 'Lake County',
 'Monticello',
 'Brouilly',
 'Monica di Sardegna',
 'Bordeaux Blanc',
 'North Coast',
 'Columbia Valley (WA)',
 'Romagna',
 'Champagne',
 'Santa Ynez Valley',
 'Chablis',
 'Mâcon-Milly Lamartine',
 'California',
 'Aglianico del Vulture',
 'Howell Mountain',
 'Calistoga',
 'South Australia',
 'Eola-Amity Hills',
 'Rías Baixas',
 'Vin de France',
 'McLaren Vale',
 'Ancient Lakes',
 'Knights Valley',
 'Vernaccia di San Gimignano',
 'Toscana',
 'Sonoma County',
 'Juliénas',
 'Régnié',
 'Finger Lakes',
 'Morellino di Scansano',
 'Santa Clara Valley',
 'Yountville',
 'Barolo',
 'Rockpile',
 'Padthaway',
 'Saint-Émilion',
 "Barbera d'Alba",
 'Santa Lucia Highlands',
 'Spring Mountain District',
 'Monterey',
 'Carmel Valley',
 'Dominio de Valdepusa',
 'Santa Cruz Mountains',
 'Chianti Classico',
 'Brunello di Montalcino',
 'Cahors',
 'Edna Valley',
 'Moulin-à-Vent',
 'Madiran',
 'Russian River Valley',
 'Alto Adige',
 'Arroyo Seco',
 'Salta',
 'Anderson Valley',
 'Campania',
 'Rosso del Veronese',
 'St.-Romain',
 'Vino Nobile di Montepulciano',
 'Nevada County',
 'Côtes du Rhône',
 'Vacqueyras',
 'Rueda',
 'Luján de Cuyo',
 'Cayuga Lake',
 "Montepulciano d'Abruzzo",
 'Santa Barbara County',
 'Diamond Mountain District',
 'San Marino',
 'Mendocino',
 'Vin de Pays des Côtes de Gascogne',
 'Vino de la Tierra de Castilla y León',
 'San Juan',
 'Adelaide Hills',
 'Sonoma Mountain',
 'Amador County',
 'St. Helena',
 'Cole Ranch',
 'Santa Maria Valley',
 'Torgiano',
 'Veneto',
 'Colli Orientali del Friuli',
 'Uco Valley',
 'Monferrato',
 'Dundee Hills',
 'Perdriel',
 'Arroyo Grande Valley',
 'Montsant',
 'Saint-Estèphe',
 'Sagrantino di Montefalco',
 'Arbois',
 'Barossa Valley',
 'Tupungato',
 'Langhe',
 'Roero',
 "Barbera d'Asti Superiore Nizza",
 'Mendocino County',
 'Côte de Nuits-Villages',
 'Prosecco di Valdobbiadene',
 'Prosecco di Conegliano',
 'Languedoc',
 'Coteaux Varois en Provence',
 'Cava',
 'Rutherglen',
 'Barossa',
 'Montrachet',
 'Heathcote',
 'Clos de Vougeot',
 'Chassagne-Montrachet',
 'Criots-Bâtard-Montrachet',
 'Clare Valley',
 'Bianco di Custoza',
 'Friuli',
 'Soave',
 'Collio',
 'Trentino',
 'Valdadige',
 'Rutherford',
 'Italy',
 'Prosecco del Veneto',
 'Prosecco di Conegliano e Valdobbiadene',
 'Graves',
 'Walla Walla Valley (WA)',
 'New York',
 'Rioja',
 'North Fork of Long Island',
 'Wahluke Slope',
 'Templeton Gap District',
 'Snipes Mountain',
 'Gavi',
 'Bierzo',
 'Long Island',
 'Muscadet Sèvre et Maine',
 'Franciacorta',
 'Meursault',
 'Niagara-On-The-Lake',
 'Carneros',
 'Ribbon Ridge',
 'Amarone della Valpolicella',
 'Chambolle-Musigny',
 'Pomerol',
 'Cannonau di Sardegna',
 'Red Mountain',
 'Isola dei Nuraghi',
 'Sta. Rita Hills',
 'Côtes du Rhône Villages',
 'Friuli Grave',
 'El Dorado',
 'Suisun Valley',
 'Côtes de Provence',
 'Lodi',
 'Venezia Giulia',
 'Yakima Valley',
 'Monterey County',
 'Chiles Valley',
 'Mercurey',
 'Calaveras County',
 'Chehalem Mountains',
 'Horse Heaven Hills',
 'Umpqua Valley',
 'Alto Adige Valle Isarco',
 'Ballard Canyon',
 'Green Valley',
 "Coteaux d'Aix-en-Provence",
 'Côtes de Provence Sainte-Victoire',
 'Sierra Foothills',
 'Yolo County',
 "Dolcetto d'Alba",
 'Bordeaux Supérieur',
 'Costières de Nîmes',
 'Bordeaux',
 'Washington',
 'Columbia Gorge (WA)',
 'Oak Knoll District',
 'Rogue Valley',
 'Northern Sonoma',
 'Soave Classico',
 'Conegliano Valdobbiadene Prosecco Superiore',
 'Piedmont',
 'Idaho',
 'Gambellara Classico',
 'Yarra Valley',
 'Great Southern',
 'Mokelumne River',
 'Los Carneros',
 'Mount Veeder',
 'Dogliani Superiore',
 'Valencia',
 'Cortona',
 'Piemonte',
 'Colli della Toscana Centrale',
 'Livermore Valley',
 'Valle de Uco',
 'Mâcon-Villages',
 'Texas',
 'Côte Chalonnaise',
 'Chorey-lès-Beaune',
 'Calchaquí Valley',
 'Coteaux Bourguignons',
 'Saint-Véran',
 'Barbaresco',
 'South Eastern Australia',
 'Temecula Valley',
 'Tasmania',
 'Cariñena',
 'Vin Santo del Chianti Classico',
 'Trento',
 'Médoc',
 'Haut-Médoc',
 'Fronsac',
 'Margaux',
 'Mornington Peninsula',
 'Verdicchio dei Castelli di Jesi Classico',
 'Vino de la Tierra de Castilla',
 'Mendocino Ridge',
 'Rosso di Montalcino',
 'Côtes de Gascogne',
 'Côtes du Lot',
 "Nebbiolo d'Alba",
 'Beaujolais Rosé',
 'Marsannay',
 'Gevrey-Chambertin',
 'Beaune',
 'Sannio',
 'Priorat',
 'Bolgheri Superiore',
 'Minervois',
 'Texas High Plains',
 'Vista Flores',
 'Australia',
 'Shenandoah Valley (CA)',
 'Blaye Côtes de Bordeaux',
 'Jumilla',
 'Coste della Sesia',
 'Yorkville Highlands',
 'Penedès',
 'Greco di Tufo',
 'Lugana',
 'Primitivo di Manduria',
 'Bardolino Classico',
 'Amarone della Valpolicella Classico',
 'Piave',
 'Gaillac',
 'Sancerre',
 'Montravel',
 'Quincy',
 'Pouilly-Fumé',
 'Coonawarra',
 'Happy Canyon of Santa Barbara',
 'Valdeorras',
 'Bizkaiko Txakolina',
 'Walla Walla Valley (OR)',
 'Isonzo del Friuli',
 "Vin de Pays d'Oc",
 'Delle Venezie',
 'Monbazillac',
 'Patrimonio',
 'Saumur-Champigny',
 'Rosso di Montepulciano',
 'Gers',
 'Crémant de Jura',
 'Vin de Liqueur',
 'Seneca Lake',
 'Naches Heights',
 'Basilicata',
 'Hudson River Region',
 'Napa-Sonoma',
 'Crémant de Bourgogne',
 'Pouilly-Fuissé',
 'Goulburn Valley',
 'Bennett Valley',
 'Paso Robles Willow Creek District',
 'Montagne-Saint-Émilion',
 'La Mancha',
 'Contra Costa County',
 'Michigan',
 'Uclés',
 'Stags Leap District',
 "Valle d'Aosta",
 'Fair Play',
 'Menetou-Salon',
 'Jerez',
 'Fronton',
 'Bergerac',
 'Salento',
 'Bordeaux Rosé',
 'Pennsylvania',
 'Les Baux de Provence',
 'Southern Oregon',
 'Old Mission Peninsula',
 'Alto Adige Terlano',
 'Dunnigan Hills',
 'Bandol',
 'Coombsville',
 'Châteauneuf-du-Pape',
 'Nuits-St.-Georges',
 'Vigneti delle Dolomiti',
 'Montefalco Rosso',
 'Umbria',
 'Faro',
 'Chénas',
 'Jurançon',
 'Saumur',
 'Alella',
 'Bardolino Chiaretto',
 'Murgia',
 'Bolgheri Sassicaia',
 'Pessac-Léognan',
 'Saint-Julien',
 'Pauillac',
 'Oakville',
 'Lalande de Pomerol',
 'Delia Nivolelli',
 'Cadillac Côtes de Bordeaux',
 'Maipú',
 'Touraine',
 'Middleburg',
 'Reuilly',
 'Gattinara',
 'Margaret River',
 'Patagonia',
 'Entre-Deux-Mers',
 'Applegate Valley',
 'Hermitage',
 'Maremma',
 'San Benito County',
 'Catalunya',
 'Ribeiro',
 'Sauternes',
 'San Luis Obispo County',
 'Bolgheri',
 'Alicante',
 'Vin de Savoie',
 'Almansa',
 'Castillon Côtes de Bordeaux',
 'Mediterranée',
 'Francs Côtes de Bordeaux',
 'Chiroubles',
 'Saint-Amour',
 'Ribeira Sacra',
 'Leelanau Peninsula',
 'Getariako Txakolina',
 'Calatayud',
 'Outer Coastal Plain',
 'Coteaux du Languedoc',
 'Sonoma-Napa',
 'Langhorne Creek',
 'Falerno del Massico',
 'Fiano di Avellino',
 'Vi de la Terra Illes Balears',
 'Santa Barbara',
 'Côtes de Bourg',
 "Barbera d'Asti Superiore",
 'Saint-Georges-Saint-Émilion',
 'Vermentino di Sardegna',
 'Bergerac Sec',
 'Morgon',
 "Virginia's Eastern Shore",
 'Colli Trevigiani',
 'Columbia Valley (OR)',
 'Listrac-Médoc',
 'Lussac Saint-Émilion',
 "Barbera d'Asti",
 'Tavel',
 "Barbera d'Alba Superiore",
 'Recioto di Soave',
 'Santenay',
 'Puligny-Montrachet',
 'Ruché di Castagnole Monferrato',
 'Valtellina Superiore',
 'Oltrepò Pavese',
 'Red Hills Lake County',
 'Toro',
 'Moulis-en-Médoc',
 'Pemberton',
 'Rosé de Loire',
 'Côtes de Bordeaux',
 'Vin Mousseux',
 'South Coast',
 'Yecla',
 'Lake Erie',
 'Potter Valley',
 'Sonoma County-Napa County',
 'Givry',
 'Buzet',
 'Valpolicella Classico Superiore Ripasso',
 'Corse',
 'Muscadet Côtes de Grandlieu',
 'Terra degli Osci',
 'Lambrusco di Modena',
 'Montefalco Sagrantino',
 'Lazio',
 'Chalk Hill',
 'Marche',
 'Cerasuolo di Vittoria Classico',
 'Frankland River',
 'Geographe',
 'Western Australia',
 'Niagara Peninsula',
 'Molise',
 'New Jersey',
 'Maury Sec',
 'Côtes du Roussillon Villages Caramany',
 'Irrouléguy',
 'Redwood Valley',
 'Friuli Aquileia',
 'Ile de Beauté',
 'Cucamonga Valley',
 "Pays d'Oc",
 'Gard',
 'Chianti',
 'Chianti Montespertoli',
 'Chianti Colli Senesi',
 'Bordeaux Clairet',
 'Fleurie',
 'Anjou Villages Brissac',
 'Fiddletown',
 'Bonnezeaux',
 'Bourgogne Hautes Côtes de Nuits',
 "Crémant d'Alsace",
 'Mâcon-Péronne',
 'Maranges',
 'Augusta',
 'Saint-Bris',
 'New Mexico',
 'Nevada',
 'Adelaide Plains',
 'Lessona',
 'Vino Spumante',
 'Boca',
 'Rivesaltes',
 'Charmes-Chambertin',
 'Valpolicella Superiore',
 'Valpolicella Classico Superiore',
 'Alto Valle del Río Negro',
 'Prosecco',
 'Paicines',
 'Condrieu',
 'Colline Pescaresi',
 'Sangiovese di Romagna Superiore',
 'Empordà',
 'Placer County',
 'Chianti Rufina',
 'Salice Salentino',
 'Mâcon-Chardonnay',
 'Ladoix',
 'Viré-Clessé',
 'Campo de Borja',
 'Mâcon-Fuissé',
 'Eden Valley',
 'Spain',
 'La Consulta',
 'Napa County-Sonoma County',
 'Solano County',
 'Colline Novaresi',
 'Adelaide',
 'Agrelo',
 'Veneto Orientale',
 'Vin de Pays des Cévennes',
 'Luberon',
 'Adelaida District',
 'Calabria',
 'Taurasi',
 'Eloro',
 'Faugères',
 'Crémant de Limoux',
 'Valdobbiadene Prosecco Superiore',
 'Irpinia',
 'Picpoul de Pinet',
 'Côtes du Marmandais',
 'Coteaux du Layon',
 'Cornas',
 'Chalone',
 'Savennières',
 'Ventoux',
 'Taburno',
 'Chinon',
 'Sebino',
 'Vouvray',
 'Columbia Gorge (OR)',
 "Trebbiano d'Abruzzo",
 'Crémant de Loire',
 'Terra Alta',
 'Victoria',
 'Valdepeñas',
 'Friuli Colli Orientali',
 'Vin Santo del Chianti',
 'Vosne-Romanée',
 'Valdobbiadene Superiore di Cartizze',
 'Recioto della Valpolicella Classico',
 'Gavi di Gavi',
 'Roero Arneis',
 'Dolcetto di Dogliani',
 'Neuquén',
 "Moscato d'Asti",
 'Saint-Nicolas-de-Bourgueil',
 'Lake Chelan',
 'Roussette de Savoie',
 'Maremma Toscana',
 'Rattlesnake Hills',
 'Alta Langa',
 'El Dorado County',
 'Napa County',
 'Côtes de Nuits Villages',
 'Bourgogne Hautes Côtes de Beaune',
 'Saint-Aubin',
 'Marin County',
 'Barsac',
 'Conero',
 'Menfi',
 'Montilla-Moriles',
 'Río Negro Valley',
 'Pernand-Vergelesses',
 'Málaga',
 'Auxey-Duresses',
 'Savigny-lès-Beaune',
 'Mâcon-Verze',
 'Saint-Joseph',
 'Vin de Pays Var',
 'Frascati Superiore',
 'Volnay',
 'Fort Ross-Seaview',
 'Mt. Harlan',
 'Quarts de Chaume',
 "Lambrusco dell'Emilia",
 'Colli Aprutini',
 "Montepulciano d'Abruzzo Colline Teramane",
 'Valpolicella Superiore Ripasso',
 'Valpolicella Ripasso',
 'Cheverny',
 'Forlì',
 'Colli Martani',
 'Cienega Valley',
 'Temecula',
 'Ghemme',
 'Carignano del Sulcis',
 'Alghero',
 'Anjou',
 'Pécharmant',
 'Minervois La Liviniere',
 'Corbières',
 'Marsala',
 'Grand Valley',
 'Colorado',
 'Okanagan Valley',
 'Clarendon',
 'Côtes du Jura',
 'Corton Les Renardes',
 'Coteaux du Giennois',
 'Aloxe-Corton',
 'Rosso Conero',
 'Falerio',
 'Verdicchio dei Castelli di Jesi',
 'Rosso Piceno',
 'Hunter Valley',
 'La Rioja',
 'Central Ranges',
 'Coteaux Varois',
 'Val di Cornia Suvereto',
 'Orvieto Classico Superiore',
 'Vin de Pays du Val de Loire',
 'Cochise County',
 'Vino de la Tierra Altiplano de Sierra Nevada',
 'Pine Mountain-Cloverdale Peak',
 'Costers del Segre',
 'Verdicchio dei Castelli di Jesi Classico Superiore',
 'Custoza Superiore',
 'Veronese',
 'Val di Neto',
 'Big Valley District-Lake County',
 'San Antonio Valley',
 'Bourgogne',
 'Petit Chablis',
 'Sierra Pelona Valley',
 'Valpolicella',
 'San Luis Obispo',
 'Famatina Valley',
 'Bâtard-Montrachet',
 'Chevalier-Montrachet',
 'Atlas Peak',
 'Puisseguin Saint-Émilion',
 'Asprinio di Aversa',
 'Orvieto Classico',
 'Bardolino',
 'Orcia',
 'Limestone Coast',
 'Mâcon-Azé',
 'Pyrenees',
 'Prosecco Superiore di Cartizze',
 'High Valley',
 'Lambrusco Grasparossa di Castelvetro',
 'San Bernabe',
 'Vermentino di Gallura',
 'Ben Lomond Mountain',
 'Argentina',
 'Morey-Saint-Denis',
 'Missouri',
 'Southeastern New England',
 'Grand River Valley',
 'Sonoita',
 'Corton-Charlemagne',
 'Emilia',
 'King Valley',
 'Pommard',
 'Costa Toscana',
 'Albana di Romagna',
 'Grands-Echezeaux',
 'Moscadello di Montalcino',
 'Mazis-Chambertin',
 'The Hamptons, Long Island',
 'Vin de Pays du Comté Tolosan',
 'Somontano',
 'Tierra del Viños de Zamora',
 'Niagara Escarpment',
 'Central Victoria',
 'Bordeaux Côtes de Francs ',
 'Shenandoah Valley',
 'Savoie',
 'Palette',
 'Var',
 'Val de Loire',
 'Coteaux du Languedoc Pic Saint Loup',
 'Primitivo del Salento',
 'Tarragona',
 'Valpolicella Classico',
 'Hautes Côtes de Nuits',
 'La Clape',
 'Vin Santo di Montepulciano',
 'Santa Barbara-Monterey',
 'Gigondas',
 'Conca de Barberà',
 'Beamsville Bench',
 'Lessini Durello',
 'Bourgueil',
 'Saint-Croix-du-Mont',
 'Lake Erie North Shore',
 'Prosecco Treviso',
 'Côte de Brouilly',
 'Mâcon-Pierreclos',
 'Salina',
 'Sainte-Foy Bordeaux',
 'Saint-Chinian',
 'Crozes-Hermitage',
 'Southern Flinders Ranges',
 'Napa-Carneros',
 'Catalonia',
 'Pouilly-Vinzelles',
 'Lago di Corbara',
 'Macon-Bussières',
 'Colli Euganei',
 'Offida Pecorino',
 'Passito di Pantelleria',
 'Illinois',
 "Sant'Antimo",
 'Vin Santo del Chianti Rufina',
 'Corse Porto Vecchio',
 'Côtes du Roussillon Villages Tautavel',
 'Côtes du Roussillon Villages',
 'Aglianico del Taburno',
 'Castel del Monte',
 'Colli di Faenza',
 'Sangiovese di Romagna',
 'Mâcon',
 'Fixin',
 'Sforzato di Valtellina',
 'Corton',
 'Latricières-Chambertin',
 'Premieres Côtes de Blaye',
 'Montagny',
 'Vin de Pays des Côtes Catalanes',
 'Malibu-Newton Canyon',
 'Vino de la Tierra Contraviesa Alpujarra',
 'Mount Harlan',
 'Côtes du Tarn',
 'Terrazze Retiche di Sondrio',
 'Pla de Bages',
 'Côtes de Provence La Londe',
 'Coteaux du Layon Chaume',
 'Sonoma-Napa-Mendocino',
 "Dolcetto d'Acqui",
 'San Francisco Bay',
 'Nagambie Lakes',
 'Côtes de Bergerac',
 'Pacherenc du Vic Bilh',
 'Chelan County',
 'Riverina',
 'California Other',
 'Saddle Rock-Malibu',
 'Echézeaux',
 'La Grande Rue',
 'Clos de la Roche',
 'Vougeot',
 'Wrattonbully',
 'Mâcon-Vergisson',
 'Lambrusco di Sorbara',
 'Mâcon-Cruzille',
 'Moon Mountain District Sonoma County',
 'Collines Rhôdaniennes',
 'Loazzolo',
 'Humboldt County',
 'Clairette de Die Méthode Dioise Ancestrale',
 'Jurançon Sec',
 'Curtefranca',
 'Monteregio di Massa Marittima',
 'Napa-Sonoma-Marin',
 'Maury',
 'Muscat de Rivesaltes',
 'Montecucco',
 'Vin de Table Francais',
 'Santa Clara County',
 'Atlantique',
 'Muscadet',
 'Sierra de Salamanca',
 'Chignin-Bergeron',
 'Beaujolais Blanc',
 'Mâcon La Roche Vineuse',
 'Côtes du Roussillon Les Aspres',
 'Côtes du Roussillon',
 'Beaujolais-Leynes',
 'Côtes de Duras',
 'Fitou',
 'Puget Sound',
 'Chambertin Clos de Bèze',
 'Corton-Rognet',
 'Corton Vergennes',
 'Chapelle-Chambertin',
 'Dogliani',
 'Anjou Villages',
 'Cadillac',
 'Sable de Camargue',
 'Pago de Arínzano',
 'Beneventano',
 'Monti Lessini',
 'McLaren Vale-Adelaide Hills',
 'Colli Piacentini',
 'Martina',
 'Lacryma Christi del Vesuvio',
 'Côtes Catalanes',
 'Vin de Pays Cité de Carcassonne',
 'Solano County Green Valley',
 'Friuli Isonzo',
 'Penisola Sorrentina',
 'California-Oregon',
 'Clear Lake',
 'Guenoc Valley',
 'Terre del Volturno',
 "Coteaux d'Ancenis",
 'Cabernet de Saumur',
 'Utiel-Requena',
 'Soave Colli Scaligeri',
 'Napa County-Sonoma County-San Joaquin County',
 'Bourgogne Gamay',
 'Terre di Franciacorta',
 'Falanghina del Sannio',
 'Rosso di Toscana',
 'Côtes de Castillon',
 'Carneros-Napa Valley',
 'Lenswood',
 'Côte de Beaune',
 "Rosé d'Anjou",
 "St. David's Bench",
 'Coteaux du Vendômois',
 'Valpolicella Ripasso Classico',
 'Chianti Colli Fiorentini',
 'Swan Creek',
 'Tierra de León',
 'Mudgee',
 'Orange',
 'New South Wales',
 'Rosso Piceno Superiore',
 'Offida Passerina',
 'Recioto di Soave Classico',
 'Montlouis-sur-Loire',
 'Vin de Pays du Lot',
 'Venezie',
 'Riviera Ligure di Ponente',
 'Tulum Valley',
 'Pompeiano',
 'Epomeo',
 'Roccamonfina',
 'Marcillac',
 'Tierra de Castilla',
 'El Pomar District',
 'Galluccio',
 'Bourgogne Epineuil',
 'Colli di Salerno',
 'Tuolumne County',
 'Côtes-du-Ventoux',
 'Tarantino',
 'Santa Margarita Ranch',
 "Brachetto d'Acqui",
 'Saint-Mont',
 'Crémant de Bordeaux',
 'Mâcon-Lugny',
 'Dolcetto di Monferrato',
 'Malibu Coast',
 'Rully',
 'Pavia',
 'Asti',
 'Carmignano',
 'Bullas',
 'Bonnes-Mares',
 'McDowell Valley',
 'Rasteau',
 'Cilento',
 'Vin de Pays des Maures',
 'Yadkin Valley',
 "Costa d'Amalfi",
 'Iowa',
 'Premieres Côtes de Bordeaux',
 'Chianti Montalbano',
 'Elkton Oregon',
 'Bourgogne Aligoté',
 'Saint-Romain',
 'Lugana Superiore',
 'Napa-Mendocino-Sonoma-Marin',
 'Cesanese del Piglio',
 'Muscat de Saint-Jean de Minervois',
 'Banyuls',
 'Friuli Venezia Giulia',
 'Monterey-Santa Barbara',
 'Sonoma County-Monterey County-Napa County',
 'Rubicone',
 'Cévennes',
 'Vittoria Frappato',
 'Muscat de Beaumes de Venise',
 'Ribera del Júcar',
 'Sonoma-Mendocino',
 'Mâcon-Uchizy',
 'Colli di Luni',
 'Soave Classico Superiore',
 'Corton Grèves',
 'Barbera del Monferrato',
 'Copertino',
 'Alta Mesa',
 'Coteaux de Verdon',
 'Lirac',
 'Kelsey Bench-Lake County',
 'Valpolicella Valpantena Superiore',
 'San Lucas',
 'British Columbia',
 'Manchuela',
 'Biferno Rosso',
 'Sonoma County-Lake County',
 'France',
 'Colli Perugini',
 "Aleatico dell'Elba",
 'Corbières-Boutenac',
 'Vin Pétillant',
 'Ohio',
 'Vin de Pays du Val de Cesse',
 'Saussignac',
 'Limoux',
 'Paso Robles Highlands District',
 'Madrid',
 'Colli Tortonesi',
 'Barco Reale di Carmignano',
 'Vino de Mesa',
 'Sonoma County-Monterey County',
 'Pouilly-Loché',
 'Noto',
 'Campi Flegrei',
 'Bendigo',
 "Vin de Pays de L'Aude",
 'Terre di Chieti',
 'Buenos Aires',
 'Vin de Pays du Gard',
 'Colline Teatine',
 "Cerasuolo d'Abruzzo",
 'Pomino',
 'Côte Rôtie',
 'Vermont',
 'Garda Classico',
 'Montenetto di Brescia',
 'Lombardy',
 'Benaco Bresciano',
 'Musigny',
 'Chambertin',
 'Clos Saint-Denis',
 'Malvasia delle Lipari',
 'Côtes de Thongue',
 'Côtes du Frontonnais',
 'Ventura County',
 'Marca Trevigiana',
 'Colli di Conegliano',
 'Chianti Colli Aretini',
 'Monterrei',
 'Mendocino-Lake',
 'Bramaterra',
 'Monterey-Santa Cruz',
 'Teroldego Rotaliano',
 'North Carolina',
 'Cortese di Gavi',
 'York Mountain',
 'Touraine Amboise',
 'Colli Bolognesi',
 'Lambrusco Reggiano',
 'Emilia-Romagna',
 'Château-Chalon',
 'Mâcon-Mancey',
 'Irancy',
 'Cigales',
 'Assisi',
 'Savennières-Roche-Aux-Moines',
 'Jujuy',
 'Montescudaio',
 'Galatina',
 'Cirò',
 'Vin de Pays des Portes de Méditerranée',
 'Alcamo',
 'Soave Superiore',
 'Brulhois',
 'Mâcon-Loché',
 'Mâcon-Vinzelles',
 'Chianti Superiore',
 'Rosazzo',
 'Orvieto',
 'Verdicchio di Matelica',
 'Columbia Valley-Walla Walla Valley',
 'Gutturnio Colli Piacentini',
 'Valtènesi',
 'Madera',
 'Ardèche',
 'Barbera del Monferrato Superiore',
 'Mâcon-Charnay',
 'Sonoma',
 'Mount Barker',
 'Corton-Pougets',
 'Cérons',
 'Coteaux du Layon Saint Aubin',
 'Gioia del Colle',
 'Kentucky',
 'Prince Edward County',
 'San Francisco Bay-Livermore Valley',
 'Extremadura',
 'Vino da Tavola',
 'Southern Fleurieu',
 'Clements Hills',
 'Vinos de Madrid',
 'Pouilly-sur-Loire',
 'Custoza',
 'Contea di Sclafani',
 "Dolcetto di Diano d'Alba",
 'Vin de Pays de la Méditerranée',
 "Vin de Pays de l'Ile de Beauté",
 'Nuragus di Cagliari',
 'Blanquette de Limoux',
 'Asolo Prosecco Superiore',
 'Venezia',
 'Sonoma County-San Joaquin County',
 'Clairette de Bellegarde',
 'Provincia di Pavia',
 "Montepulciano d'Abruzzo Cerasuolo",
 'Colline Lucchesi',
 'Emporadà-Costa Brava',
 'Fara',
 'Lison-Pramaggiore',
 'Côtes du Luberon',
 'Lambrusco Salamino di Santa Croce',
 'Recioto della Valpolicella',
 'Canon-Fronsac',
 'Western Connecticut Highlands',
 'River Junction',
 'Passito di Noto',
 'Vin de Pays des Alpilles',
 'Grampians',
 'Currency Creek',
 'Cour-Cheverny',
 'Muscadet Sèvre et Maine Clisson',
 'Amarone della Valpolicella Valpantena',
 'Aude Hauterive',
 'Ribera del Guadiana',
 'Toledo',
 'Monterey-Santa Barbara-Sonoma',
 ...]

In [ ]:
reviews.points - review_mean

0       -1.434037
1       -1.434037
2       -1.434037
3       -1.434037
4       -1.434037
           ...
65494    1.565963
65495    1.565963
65496    1.565963
65497    1.565963
65498    1.565963
Name: points, Length: 65499, dtype: float64

In [ ]:
reviews.country + " - " + reviews.region_1

0                    Italy - Etna
1                             NaN
2          US - Willamette Valley
3        US - Lake Michigan Shore
4          US - Willamette Valley
                   ...
65494            France - Chablis
65495    Australia - McLaren Vale
65496       US - Dry Creek Valley
65497            US - Napa Valley
65498               Spain - Jerez
Length: 65499, dtype: object