In [ ]:
import pandas as pd
url = "https://gist.githubusercontent.com/clairehq/79acab35be50eaf1c383948ed3fd1129/raw/407a02139ae1e134992b90b4b2b8c329b3d73a6a/winemag-data-130k-v2.csv"
reviews = pd.read_csv(url)
# reviews = pd.read_csv(url,index_col = 0)
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
reviews = reviews.set_index(['Unnamed: 0'])

In [ ]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
Unnamed: 0,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

**[link text](https://)describe()**

works for both series and dataframes

In [ ]:
reviews.describe()

             points         price
count  65499.000000  60829.000000
mean      88.434037     35.232932
std        3.030310     39.477858
min       80.000000      4.000000
25%       86.000000     17.000000
50%       88.000000     25.000000
75%       91.000000     42.000000
max      100.000000   2500.000000

In [ ]:
reviews.points.describe()

count    65499.000000
mean        88.434037
std          3.030310
min         80.000000
25%         86.000000
50%         88.000000
75%         91.000000
max        100.000000
Name: points, dtype: float64

In [ ]:
reviews.taster_name.describe()

count          51856
unique            19
top       Roger Voss
freq           13045
Name: taster_name, dtype: object

Mean Median Mode

In [ ]:
reviews.points.mean()

np.float64(88.43403716087269)

In [ ]:
reviews.points.median()

88.0

In [ ]:
reviews.points.mode()

0    87
Name: points, dtype: int64

In [ ]:
reviews.points.std()

3.0303102985612185

In [ ]:
reviews.points.min()

80

In [ ]:
reviews.points.max()

100

In [ ]:
reviews.points.sum()

np.int64(5792341)

In [ ]:
reviews.points.idxmax()

np.int64(345)

In [ ]:
reviews.iloc[345]

country                                                          Australia
description              This wine contains some material over 100 year...
designation                                                           Rare
points                                                                 100
price                                                                350.0
province                                                          Victoria
region_1                                                        Rutherglen
region_2                                                               NaN
taster_name                                                 Joe Czerwinski
taster_twitter_handle                                               @JoeCz
title                    Chambers Rosewood Vineyards NV Rare Muscat (Ru...
variety                                                             Muscat
winery                                         Chambers Rosewood Vineyards
Name: 345, dtype: object

In [ ]:
reviews.points.idxmin()

np.int64(344)

In [ ]:
reviews.iloc[344,0]

'Chile'

In [ ]:
reviews[['points', 'price']].corr()

        points   price
points  1.0000  0.4309
price   0.4309  1.0000

In [ ]:
reviews.taster_name.unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams',
       'Christina Pickard'], dtype=object)

In [ ]:
reviews.taster_name.nunique()

19

In [ ]:
reviews.taster_name.value_counts()

taster_name
Roger Voss            13045
Michael Schachner      7752
Kerin O’Keefe          5313
Paul Gregutt           4851
Virginie Boone         4696
Matt Kettmann          3035
Joe Czerwinski         2605
Sean P. Sullivan       2358
Anna Lee C. Iijima     2134
Jim Gordon             2032
Anne Krebiehl MW       1769
Lauren Buzzeo           938
Susan Kostrzewa         593
Jeff Jenssen            234
Mike DeSimone           231
Alexander Peartree      210
Carrie Dykes             45
Fiona Adams              11
Christina Pickard         4
Name: count, dtype: int64

**map()**

map produces a series

In [ ]:
review_points_mean = reviews.points.mean()
def remean_points_map(p):
  return p - review_points_mean
remean_points_map(87)

np.float64(-1.4340371608726912)

In [ ]:
review_points_mean = reviews.points.mean()
def remean_points_map(p):
  return p - review_points_mean

reviews.points.map(remean_points_map)

Unnamed: 0
0       -1.434037
1       -1.434037
2       -1.434037
3       -1.434037
4       -1.434037
           ...
65494    1.565963
65495    1.565963
65496    1.565963
65497    1.565963
65498    1.565963
Name: points, Length: 65499, dtype: float64

In [ ]:
review_points_mean = reviews.points.mean()
reviews.points.map(lambda p : p - review_points_mean)

Unnamed: 0
0       -1.434037
1       -1.434037
2       -1.434037
3       -1.434037
4       -1.434037
           ...
65494    1.565963
65495    1.565963
65496    1.565963
65497    1.565963
65498    1.565963
Name: points, Length: 65499, dtype: float64

**apply()**

produces an entire dataframe

axis = 0 or axis = 'index' or nothing (column wise)

axis = 1 or axis = 'columns' (row wise)

In [ ]:
row = reviews.iloc[0]
row.points

np.int64(87)

In [ ]:
def remean_points(row):
  row.points = row.points - review_points_mean
  return row

In [ ]:
reviews.apply(remean_points, axis = 'columns')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
Unnamed: 0,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.434037,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.434037,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.434037,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.434037,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.434037,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65494,France,Made from young vines from the Vaulorent porti...,Fourchaume Premier Cru,1.565963,45.0,Burgundy,Chablis,NaN,Roger Voss,@vossroger,William Fèvre 2005 Fourchaume Premier Cru (Ch...,Chardonnay,William Fèvre
65495,Australia,"This is a big, fat, almost sweet-tasting Caber...",NaN,1.565963,22.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Tapestry 2005 Cabernet Sauvignon (McLaren Vale),Cabernet Sauvignon,Tapestry
65496,US,"Much improved over the unripe 2005, Fritz's 20...",Estate,1.565963,20.0,California,Dry Creek Valley,Sonoma,NaN,NaN,Fritz 2006 Estate Sauvignon Blanc (Dry Creek V...,Sauvignon Blanc,Fritz
65497,US,This wine wears its 15.8% alcohol better than ...,Block 24,1.565963,31.0,California,Napa Valley,Napa,NaN,NaN,Hendry 2004 Block 24 Primitivo (Napa Valley),Primitivo,Hendry
65498,Spain,"A unique take on Manzanilla Sherry, which is o...",Manzanilla,1.565963,10.0,Andalucia,Jerez,NaN,Michael Schachner,@wineschach,Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...,Sherry,Bodegas Dios Baco S.L.

In [ ]:
def remean_column(col):
  if col.name == 'points':
    return col - review_points_mean
  return col
reviews.apply(remean_column, axis = 'index')

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
Unnamed: 0,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.434037,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.434037,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.434037,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.434037,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.434037,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65494,France,Made from young vines from the Vaulorent porti...,Fourchaume Premier Cru,1.565963,45.0,Burgundy,Chablis,NaN,Roger Voss,@vossroger,William Fèvre 2005 Fourchaume Premier Cru (Ch...,Chardonnay,William Fèvre
65495,Australia,"This is a big, fat, almost sweet-tasting Caber...",NaN,1.565963,22.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Tapestry 2005 Cabernet Sauvignon (McLaren Vale),Cabernet Sauvignon,Tapestry
65496,US,"Much improved over the unripe 2005, Fritz's 20...",Estate,1.565963,20.0,California,Dry Creek Valley,Sonoma,NaN,NaN,Fritz 2006 Estate Sauvignon Blanc (Dry Creek V...,Sauvignon Blanc,Fritz
65497,US,This wine wears its 15.8% alcohol better than ...,Block 24,1.565963,31.0,California,Napa Valley,Napa,NaN,NaN,Hendry 2004 Block 24 Primitivo (Napa Valley),Primitivo,Hendry
65498,Spain,"A unique take on Manzanilla Sherry, which is o...",Manzanilla,1.565963,10.0,Andalucia,Jerez,NaN,Michael Schachner,@wineschach,Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...,Sherry,Bodegas Dios Baco S.L.

In [ ]:
def remean_column(col):
  if col.name == 'points':
    return col - review_points_mean
  return col
reviews.apply(remean_column)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
Unnamed: 0,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.434037,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.434037,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.434037,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.434037,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.434037,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65494,France,Made from young vines from the Vaulorent porti...,Fourchaume Premier Cru,1.565963,45.0,Burgundy,Chablis,NaN,Roger Voss,@vossroger,William Fèvre 2005 Fourchaume Premier Cru (Ch...,Chardonnay,William Fèvre
65495,Australia,"This is a big, fat, almost sweet-tasting Caber...",NaN,1.565963,22.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Tapestry 2005 Cabernet Sauvignon (McLaren Vale),Cabernet Sauvignon,Tapestry
65496,US,"Much improved over the unripe 2005, Fritz's 20...",Estate,1.565963,20.0,California,Dry Creek Valley,Sonoma,NaN,NaN,Fritz 2006 Estate Sauvignon Blanc (Dry Creek V...,Sauvignon Blanc,Fritz
65497,US,This wine wears its 15.8% alcohol better than ...,Block 24,1.565963,31.0,California,Napa Valley,Napa,NaN,NaN,Hendry 2004 Block 24 Primitivo (Napa Valley),Primitivo,Hendry
65498,Spain,"A unique take on Manzanilla Sherry, which is o...",Manzanilla,1.565963,10.0,Andalucia,Jerez,NaN,Michael Schachner,@wineschach,Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...,Sherry,Bodegas Dios Baco S.L.

In [ ]:
def describe_column(col):
  if col.dtype != 'object':
    return col.describe()
reviews.apply(describe_column)

country                                                               None
description                                                           None
designation                                                           None
points                   count    65499.000000
mean        88.434037
st...
price                    count    60829.000000
mean        35.232932
st...
province                                                              None
region_1                                                              None
region_2                                                              None
taster_name                                                           None
taster_twitter_handle                                                 None
title                                                                 None
variety                                                               None
winery                                                                None
dtype: object

In [ ]:
def describe_column(col):
  return col.describe()
reviews.apply(describe_column)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
25%,NaN,NaN,NaN,86.000000,17.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,88.000000,25.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,91.000000,42.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
count,65467,65499,46588,65499.000000,60829.000000,65467,54744,25170,51856,49467,65499,65499,65499
freq,27177,3,999,NaN,NaN,18122,2226,5420,13045,13045,6,6657,119
max,NaN,NaN,NaN,100.000000,2500.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,88.434037,35.232932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,80.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,3.030310,39.477858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,US,"Cigar box, café au lait, and dried tobacco aro...",Reserve,NaN,NaN,California,Napa Valley,Central Coast,Roger Voss,@vossroger,Korbel NV Brut Sparkling (California),Pinot Noir,Wines & Winemakers
unique,41,62824,24187,NaN,NaN,385,1111,17,19,15,62466,590,13549

In [ ]:
def normalize_numeric_only(col):
  if col.dtype != 'object':
    return col - col.mean()
  return col
reviews.apply(normalize_numeric_only)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
Unnamed: 0,,,,,,,,,,,,,
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.434037,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.434037,-20.232932,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.434037,-21.232932,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.434037,-22.232932,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.434037,29.767068,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65494,France,Made from young vines from the Vaulorent porti...,Fourchaume Premier Cru,1.565963,9.767068,Burgundy,Chablis,NaN,Roger Voss,@vossroger,William Fèvre 2005 Fourchaume Premier Cru (Ch...,Chardonnay,William Fèvre
65495,Australia,"This is a big, fat, almost sweet-tasting Caber...",NaN,1.565963,-13.232932,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Tapestry 2005 Cabernet Sauvignon (McLaren Vale),Cabernet Sauvignon,Tapestry
65496,US,"Much improved over the unripe 2005, Fritz's 20...",Estate,1.565963,-15.232932,California,Dry Creek Valley,Sonoma,NaN,NaN,Fritz 2006 Estate Sauvignon Blanc (Dry Creek V...,Sauvignon Blanc,Fritz
65497,US,This wine wears its 15.8% alcohol better than ...,Block 24,1.565963,-4.232932,California,Napa Valley,Napa,NaN,NaN,Hendry 2004 Block 24 Primitivo (Napa Valley),Primitivo,Hendry
65498,Spain,"A unique take on Manzanilla Sherry, which is o...",Manzanilla,1.565963,-25.232932,Andalucia,Jerez,NaN,Michael Schachner,@wineschach,Bodegas Dios Baco S.L. NV Manzanilla Sherry (J...,Sherry,Bodegas Dios Baco S.L.

In [ ]:
reviews.points - review_points_mean

Unnamed: 0
0       -1.434037
1       -1.434037
2       -1.434037
3       -1.434037
4       -1.434037
           ...
65494    1.565963
65495    1.565963
65496    1.565963
65497    1.565963
65498    1.565963
Name: points, Length: 65499, dtype: float64

In [ ]:
reviews.groupby('points').price.min()

points
80       5.0
81       5.0
82       5.0
83       4.0
84       4.0
85       4.0
86       4.0
87       5.0
88       6.0
89       7.0
90       8.0
91       7.0
92      11.0
93      13.0
94      13.0
95      20.0
96      27.0
97      40.0
98      50.0
99      75.0
100    150.0
Name: price, dtype: float64

In [ ]:
reviews.groupby('points').price.mean()

points
80      15.929032
81      17.963087
82      18.829787
83      18.181028
84      19.336691
85      20.049611
86      21.969813
87      24.904437
88      28.515923
89      32.239924
90      36.871516
91      42.728039
92      51.383773
93      63.442095
94      80.401801
95     109.650080
96     162.485477
97     228.636364
98     279.526316
99     325.600000
100    328.625000
Name: price, dtype: float64

In [ ]:
reviews.groupby('points').price.sum()

points
80       2469.0
81       5353.0
82      16815.0
83      25108.0
84      63347.0
85      95376.0
86     126634.0
87     204316.0
88     222966.0
89     170388.0
90     264590.0
91     238337.0
92     229891.0
93     188994.0
94     142874.0
95      68312.0
96      39159.0
97      20120.0
98      10622.0
99       4884.0
100      2629.0
Name: price, dtype: float64

In [ ]:
reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

/tmp/ipykernel_10772/506966275.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

winery
1+1=3                                     1+1=3 NV Rosé Sparkling (Cava)
10 Knots                            10 Knots 2010 Viognier (Paso Robles)
100 Percent Wine              100 Percent Wine 2015 Moscato (California)
1000 Stories           1000 Stories 2013 Bourbon Barrel Aged Zinfande...
1070 Green                  1070 Green 2011 Sauvignon Blanc (Rutherford)
                                             ...
Órale                       Órale 2011 Cabronita Red (Santa Ynez Valley)
Öko                    Öko 2013 Made With Organically Grown Grapes Ma...
Ökonomierat Rebholz    Ökonomierat Rebholz 2007 Von Rotliegenden Spät...
àMaurice               àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                                    Štoka 2009 Izbrani Teran (Kras)
Length: 13549, dtype: object

In [ ]:
reviews.groupby('winery').title.first()

winery
1+1=3                                     1+1=3 NV Rosé Sparkling (Cava)
10 Knots                            10 Knots 2010 Viognier (Paso Robles)
100 Percent Wine              100 Percent Wine 2015 Moscato (California)
1000 Stories           1000 Stories 2013 Bourbon Barrel Aged Zinfande...
1070 Green                  1070 Green 2011 Sauvignon Blanc (Rutherford)
                                             ...
Órale                       Órale 2011 Cabronita Red (Santa Ynez Valley)
Öko                    Öko 2013 Made With Organically Grown Grapes Ma...
Ökonomierat Rebholz    Ökonomierat Rebholz 2007 Von Rotliegenden Spät...
àMaurice               àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                                    Štoka 2009 Izbrani Teran (Kras)
Name: title, Length: 13549, dtype: object

In [ ]:
reviews.groupby('country').points.mean()

country
Argentina                 86.681699
Armenia                   87.000000
Australia                 88.582838
Austria                   89.992661
Bosnia and Herzegovina    85.000000
Brazil                    84.354839
Bulgaria                  87.911765
Canada                    89.212963
Chile                     86.574402
Croatia                   87.204545
Cyprus                    86.333333
Czech Republic            86.833333
England                   91.250000
France                    88.871487
Georgia                   87.567568
Germany                   89.808754
Greece                    87.231405
Hungary                   89.426230
India                     90.750000
Israel                    88.189189
Italy                     88.566417
Lebanon                   87.650000
Luxembourg                88.250000
Macedonia                 88.166667
Mexico                    85.967742
Moldova                   87.100000
Morocco                   88.636364
New Zealand               88.237381
Peru                      84.000000
Portugal                  88.134323
Romania                   86.522388
Serbia                    87.857143
Slovakia                  87.000000
Slovenia                  87.974359
South Africa              88.074627
Spain                     87.259607
Switzerland               87.750000
Turkey                    88.232558
US                        88.556095
Ukraine                   82.800000
Uruguay                   86.655738
Name: points, dtype: float64

In [ ]:
reviews.groupby('points').price.mean()

points
80      15.929032
81      17.963087
82      18.829787
83      18.181028
84      19.336691
85      20.049611
86      21.969813
87      24.904437
88      28.515923
89      32.239924
90      36.871516
91      42.728039
92      51.383773
93      63.442095
94      80.401801
95     109.650080
96     162.485477
97     228.636364
98     279.526316
99     325.600000
100    328.625000
Name: price, dtype: float64

In [ ]:
reviews.groupby('points').price.count()

points
80      155
81      298
82      893
83     1381
84     3276
85     4757
86     5764
87     8204
88     7819
89     5285
90     7176
91     5578
92     4474
93     2979
94     1777
95      623
96      241
97       88
98       38
99       15
100       8
Name: price, dtype: int64

In [ ]:
reviews.groupby(['country', 'province']).price.mean()

country    province
Argentina  Mendoza Province    24.122222
           Other               20.464419
Armenia    Armenia             14.000000
Australia  Australia Other     13.437500
           New South Wales     22.000000
                                 ...
Uruguay    Juanico             40.375000
           Montevideo          24.800000
           Progreso            17.200000
           San Jose            30.000000
           Uruguay             22.857143
Name: price, Length: 385, dtype: float64